type = "standalone"

[standalone]
username = "Administrator"
password = "password"
conn-string = "couchbase://127.0.0.1"
default_bucket = "test"
default_scope = "_default"
default_collection = "_default"

