// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionBeginAttemptRequest {
    #[prost(string, tag = "1")]
    pub bucket_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub transaction_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionBeginAttemptResponse {
    #[prost(string, tag = "1")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub attempt_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionCommitRequest {
    #[prost(string, tag = "1")]
    pub bucket_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attempt_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionCommitResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRollbackRequest {
    #[prost(string, tag = "1")]
    pub bucket_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attempt_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionRollbackResponse {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionGetRequest {
    #[prost(string, tag = "1")]
    pub bucket_name: ::prost::alloc::string::String,
    /// transaction_id and attempt_id are optional to allow read-only transactions.
    /// clients are not permitted to use this functionality to optimize
    /// non-read-only transactions.
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attempt_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub scope_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub collection_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub key: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionGetResponse {
    #[prost(uint64, tag = "1")]
    pub cas: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionInsertRequest {
    #[prost(string, tag = "1")]
    pub bucket_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attempt_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub scope_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub collection_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub key: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "7")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionInsertResponse {
    #[prost(uint64, tag = "1")]
    pub cas: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionReplaceRequest {
    #[prost(string, tag = "1")]
    pub bucket_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attempt_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub scope_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub collection_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub cas: u64,
    #[prost(bytes = "vec", tag = "8")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionReplaceResponse {
    #[prost(uint64, tag = "1")]
    pub cas: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionRemoveRequest {
    #[prost(string, tag = "1")]
    pub bucket_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub attempt_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub scope_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub collection_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub key: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub cas: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TransactionRemoveResponse {
    #[prost(uint64, tag = "1")]
    pub cas: u64,
}
/// Generated client implementations.
pub mod transactions_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct TransactionsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl TransactionsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> TransactionsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> TransactionsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            TransactionsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn transaction_begin_attempt(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionBeginAttemptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionBeginAttemptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.transactions.v1.TransactionsService/TransactionBeginAttempt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "couchbase.transactions.v1.TransactionsService",
                        "TransactionBeginAttempt",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transaction_commit(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionCommitRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionCommitResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.transactions.v1.TransactionsService/TransactionCommit",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "couchbase.transactions.v1.TransactionsService",
                        "TransactionCommit",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transaction_rollback(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionRollbackRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionRollbackResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.transactions.v1.TransactionsService/TransactionRollback",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "couchbase.transactions.v1.TransactionsService",
                        "TransactionRollback",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transaction_get(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionGetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionGetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.transactions.v1.TransactionsService/TransactionGet",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "couchbase.transactions.v1.TransactionsService",
                        "TransactionGet",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transaction_insert(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionInsertRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionInsertResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.transactions.v1.TransactionsService/TransactionInsert",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "couchbase.transactions.v1.TransactionsService",
                        "TransactionInsert",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transaction_replace(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionReplaceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionReplaceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.transactions.v1.TransactionsService/TransactionReplace",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "couchbase.transactions.v1.TransactionsService",
                        "TransactionReplace",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn transaction_remove(
            &mut self,
            request: impl tonic::IntoRequest<super::TransactionRemoveRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TransactionRemoveResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.transactions.v1.TransactionsService/TransactionRemove",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "couchbase.transactions.v1.TransactionsService",
                        "TransactionRemove",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
