// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRequest {
    #[prost(string, optional, tag = "1")]
    pub bucket_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub scope_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub statement: ::prost::alloc::string::String,
    #[prost(bool, optional, tag = "4")]
    pub read_only: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub prepared: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "6")]
    pub tuning_options: ::core::option::Option<query_request::TuningOptions>,
    #[prost(string, optional, tag = "7")]
    pub client_context_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "query_request::ScanConsistency", optional, tag = "8")]
    pub scan_consistency: ::core::option::Option<i32>,
    #[prost(bytes = "vec", repeated, tag = "9")]
    pub positional_parameters: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(map = "string, bytes", tag = "10")]
    pub named_parameters: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::vec::Vec<u8>,
    >,
    #[prost(bool, optional, tag = "11")]
    pub flex_index: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "12")]
    pub preserve_expiry: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "13")]
    pub consistent_with: ::prost::alloc::vec::Vec<super::super::kv::v1::MutationToken>,
    #[prost(enumeration = "query_request::DurabilityLevel", optional, tag = "15")]
    pub durability_level: ::core::option::Option<i32>,
    #[prost(enumeration = "query_request::ProfileMode", optional, tag = "14")]
    pub profile_mode: ::core::option::Option<i32>,
}
/// Nested message and enum types in `QueryRequest`.
pub mod query_request {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct TuningOptions {
        #[prost(uint32, optional, tag = "1")]
        pub max_parallelism: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "2")]
        pub pipeline_batch: ::core::option::Option<u32>,
        #[prost(uint32, optional, tag = "3")]
        pub pipeline_cap: ::core::option::Option<u32>,
        #[prost(message, optional, tag = "4")]
        pub scan_wait: ::core::option::Option<::prost_types::Duration>,
        #[prost(uint32, optional, tag = "5")]
        pub scan_cap: ::core::option::Option<u32>,
        #[prost(bool, optional, tag = "6")]
        pub disable_metrics: ::core::option::Option<bool>,
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ScanConsistency {
        NotBounded = 0,
        RequestPlus = 1,
    }
    impl ScanConsistency {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                ScanConsistency::NotBounded => "SCAN_CONSISTENCY_NOT_BOUNDED",
                ScanConsistency::RequestPlus => "SCAN_CONSISTENCY_REQUEST_PLUS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SCAN_CONSISTENCY_NOT_BOUNDED" => Some(Self::NotBounded),
                "SCAN_CONSISTENCY_REQUEST_PLUS" => Some(Self::RequestPlus),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DurabilityLevel {
        None = 0,
        Majority = 1,
        MajorityAndPersistToActive = 2,
        PersistToMajority = 3,
    }
    impl DurabilityLevel {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                DurabilityLevel::None => "DURABILITY_LEVEL_NONE",
                DurabilityLevel::Majority => "DURABILITY_LEVEL_MAJORITY",
                DurabilityLevel::MajorityAndPersistToActive => {
                    "DURABILITY_LEVEL_MAJORITY_AND_PERSIST_TO_ACTIVE"
                }
                DurabilityLevel::PersistToMajority => {
                    "DURABILITY_LEVEL_PERSIST_TO_MAJORITY"
                }
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "DURABILITY_LEVEL_NONE" => Some(Self::None),
                "DURABILITY_LEVEL_MAJORITY" => Some(Self::Majority),
                "DURABILITY_LEVEL_MAJORITY_AND_PERSIST_TO_ACTIVE" => {
                    Some(Self::MajorityAndPersistToActive)
                }
                "DURABILITY_LEVEL_PERSIST_TO_MAJORITY" => Some(Self::PersistToMajority),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ProfileMode {
        Off = 0,
        Phases = 1,
        Timings = 2,
    }
    impl ProfileMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                ProfileMode::Off => "PROFILE_MODE_OFF",
                ProfileMode::Phases => "PROFILE_MODE_PHASES",
                ProfileMode::Timings => "PROFILE_MODE_TIMINGS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PROFILE_MODE_OFF" => Some(Self::Off),
                "PROFILE_MODE_PHASES" => Some(Self::Phases),
                "PROFILE_MODE_TIMINGS" => Some(Self::Timings),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryResponse {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub rows: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, optional, tag = "2")]
    pub meta_data: ::core::option::Option<query_response::MetaData>,
}
/// Nested message and enum types in `QueryResponse`.
pub mod query_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct MetaData {
        #[prost(string, tag = "1")]
        pub request_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub client_context_id: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "3")]
        pub metrics: ::core::option::Option<meta_data::Metrics>,
        #[prost(enumeration = "meta_data::Status", tag = "4")]
        pub status: i32,
        #[prost(message, repeated, tag = "5")]
        pub warnings: ::prost::alloc::vec::Vec<meta_data::Warning>,
        #[prost(bytes = "vec", optional, tag = "6")]
        pub profile: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
        #[prost(bytes = "vec", tag = "7")]
        pub signature: ::prost::alloc::vec::Vec<u8>,
    }
    /// Nested message and enum types in `MetaData`.
    pub mod meta_data {
        #[allow(clippy::derive_partial_eq_without_eq)]
        #[derive(Clone, PartialEq, ::prost::Message)]
        pub struct Warning {
            #[prost(uint32, tag = "1")]
            pub code: u32,
            #[prost(string, tag = "2")]
            pub message: ::prost::alloc::string::String,
        }
        #[allow(clippy::derive_partial_eq_without_eq)]
        #[derive(Clone, Copy, PartialEq, ::prost::Message)]
        pub struct Metrics {
            #[prost(message, optional, tag = "1")]
            pub elapsed_time: ::core::option::Option<::prost_types::Duration>,
            #[prost(message, optional, tag = "2")]
            pub execution_time: ::core::option::Option<::prost_types::Duration>,
            #[prost(uint64, tag = "3")]
            pub result_count: u64,
            #[prost(uint64, tag = "4")]
            pub result_size: u64,
            #[prost(uint64, tag = "5")]
            pub mutation_count: u64,
            #[prost(uint64, tag = "6")]
            pub sort_count: u64,
            #[prost(uint64, tag = "7")]
            pub error_count: u64,
            #[prost(uint64, tag = "8")]
            pub warning_count: u64,
        }
        #[derive(
            Clone,
            Copy,
            Debug,
            PartialEq,
            Eq,
            Hash,
            PartialOrd,
            Ord,
            ::prost::Enumeration
        )]
        #[repr(i32)]
        pub enum Status {
            Running = 0,
            Success = 1,
            Errors = 2,
            Completed = 3,
            Stopped = 4,
            Timeout = 5,
            Closed = 6,
            Fatal = 7,
            Aborted = 8,
            Unknown = 9,
        }
        impl Status {
            /// String value of the enum field names used in the ProtoBuf definition.
            ///
            /// The values are not transformed in any way and thus are considered stable
            /// (if the ProtoBuf definition does not change) and safe for programmatic use.
            pub fn as_str_name(&self) -> &'static str {
                match self {
                    Status::Running => "STATUS_RUNNING",
                    Status::Success => "STATUS_SUCCESS",
                    Status::Errors => "STATUS_ERRORS",
                    Status::Completed => "STATUS_COMPLETED",
                    Status::Stopped => "STATUS_STOPPED",
                    Status::Timeout => "STATUS_TIMEOUT",
                    Status::Closed => "STATUS_CLOSED",
                    Status::Fatal => "STATUS_FATAL",
                    Status::Aborted => "STATUS_ABORTED",
                    Status::Unknown => "STATUS_UNKNOWN",
                }
            }
            /// Creates an enum from field names used in the ProtoBuf definition.
            pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
                match value {
                    "STATUS_RUNNING" => Some(Self::Running),
                    "STATUS_SUCCESS" => Some(Self::Success),
                    "STATUS_ERRORS" => Some(Self::Errors),
                    "STATUS_COMPLETED" => Some(Self::Completed),
                    "STATUS_STOPPED" => Some(Self::Stopped),
                    "STATUS_TIMEOUT" => Some(Self::Timeout),
                    "STATUS_CLOSED" => Some(Self::Closed),
                    "STATUS_FATAL" => Some(Self::Fatal),
                    "STATUS_ABORTED" => Some(Self::Aborted),
                    "STATUS_UNKNOWN" => Some(Self::Unknown),
                    _ => None,
                }
            }
        }
    }
}
/// Generated client implementations.
pub mod query_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct QueryServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl QueryServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> QueryServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            QueryServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn query(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::QueryResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.query.v1.QueryService/Query",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("couchbase.query.v1.QueryService", "Query"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
