// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ViewQueryRequest {
    #[prost(string, tag = "8")]
    pub bucket_name: ::prost::alloc::string::String,
    #[prost(string, tag = "1")]
    pub design_document_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub view_name: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "3")]
    pub skip: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub limit: ::core::option::Option<u32>,
    #[prost(enumeration = "view_query_request::ScanConsistency", optional, tag = "5")]
    pub scan_consistency: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "6")]
    pub reduce: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "7")]
    pub group: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "9")]
    pub group_level: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "10")]
    pub key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "11")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "12")]
    pub start_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "13")]
    pub end_key: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bool, optional, tag = "14")]
    pub inclusive_end: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "15")]
    pub start_key_doc_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "16")]
    pub end_key_doc_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "view_query_request::ErrorMode", optional, tag = "17")]
    pub on_error: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "18")]
    pub debug: ::core::option::Option<bool>,
    #[prost(enumeration = "view_query_request::Namespace", optional, tag = "19")]
    pub namespace: ::core::option::Option<i32>,
    #[prost(enumeration = "view_query_request::Order", optional, tag = "20")]
    pub order: ::core::option::Option<i32>,
}
/// Nested message and enum types in `ViewQueryRequest`.
pub mod view_query_request {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ScanConsistency {
        NotBounded = 0,
        RequestPlus = 1,
        UpdateAfter = 2,
    }
    impl ScanConsistency {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                ScanConsistency::NotBounded => "SCAN_CONSISTENCY_NOT_BOUNDED",
                ScanConsistency::RequestPlus => "SCAN_CONSISTENCY_REQUEST_PLUS",
                ScanConsistency::UpdateAfter => "SCAN_CONSISTENCY_UPDATE_AFTER",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "SCAN_CONSISTENCY_NOT_BOUNDED" => Some(Self::NotBounded),
                "SCAN_CONSISTENCY_REQUEST_PLUS" => Some(Self::RequestPlus),
                "SCAN_CONSISTENCY_UPDATE_AFTER" => Some(Self::UpdateAfter),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ErrorMode {
        Continue = 0,
        Stop = 1,
    }
    impl ErrorMode {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                ErrorMode::Continue => "ERROR_MODE_CONTINUE",
                ErrorMode::Stop => "ERROR_MODE_STOP",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ERROR_MODE_CONTINUE" => Some(Self::Continue),
                "ERROR_MODE_STOP" => Some(Self::Stop),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Namespace {
        Production = 0,
        Development = 1,
    }
    impl Namespace {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Namespace::Production => "NAMESPACE_PRODUCTION",
                Namespace::Development => "NAMESPACE_DEVELOPMENT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NAMESPACE_PRODUCTION" => Some(Self::Production),
                "NAMESPACE_DEVELOPMENT" => Some(Self::Development),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Order {
        Ascending = 0,
        Descending = 1,
    }
    impl Order {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Order::Ascending => "ORDER_ASCENDING",
                Order::Descending => "ORDER_DESCENDING",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ORDER_ASCENDING" => Some(Self::Ascending),
                "ORDER_DESCENDING" => Some(Self::Descending),
                _ => None,
            }
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ViewQueryResponse {
    #[prost(message, repeated, tag = "1")]
    pub rows: ::prost::alloc::vec::Vec<view_query_response::Row>,
    #[prost(message, optional, tag = "2")]
    pub meta_data: ::core::option::Option<view_query_response::MetaData>,
}
/// Nested message and enum types in `ViewQueryResponse`.
pub mod view_query_response {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Row {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
        #[prost(bytes = "vec", tag = "2")]
        pub key: ::prost::alloc::vec::Vec<u8>,
        #[prost(bytes = "vec", tag = "3")]
        pub value: ::prost::alloc::vec::Vec<u8>,
    }
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct MetaData {
        #[prost(uint64, tag = "1")]
        pub total_rows: u64,
        #[prost(bytes = "vec", tag = "2")]
        pub debug: ::prost::alloc::vec::Vec<u8>,
    }
}
/// Generated client implementations.
pub mod view_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct ViewServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ViewServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ViewServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ViewServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            ViewServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn view_query(
            &mut self,
            request: impl tonic::IntoRequest<super::ViewQueryRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ViewQueryResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/couchbase.view.v1.ViewService/ViewQuery",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("couchbase.view.v1.ViewService", "ViewQuery"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
