on:
  pull_request:
  push:
    branches:
      - main
name: Clippy check

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: actions/checkout@v4
      - name: Run Clippy
        run: |
          cargo clippy --version
          cargo clippy --all-targets --all-features
