name: Publish crates
on:
  push:
    tags:
      - v*

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-release
        run: cargo install cargo-release --version 1.1.1 --locked

      - name: Dry run
        run: cargo release --workspace --no-confirm --exclude protostellar

  publish:
    needs: dry-run
    runs-on: ubuntu-latest
    environment: crates-io
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-release
        run: cargo install cargo-release --version 1.1.1 --locked

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        run: cargo release --workspace --no-confirm --execute --exclude protostellar
