on:
  pull_request:
  push:
    branches:
      - main
name: Rustfmt

jobs:
  cargo_fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - uses: actions/checkout@v4
      - name: Run fmt
        run: cargo fmt --check
