name: Run Tests

on:
  push:
    tags:
      - v*
    branches:
      - nativex
  pull_request:

jobs:
  test:
    name: Integration Test

    strategy:
      matrix:
        server:
          - 7.6.2
          - 7.2.2
          - 7.1.1
          - 7.0.3

    runs-on: ubuntu-latest
    steps:
      - name: Install cbdinocluster
        run: |
          mkdir -p "$HOME/bin"
          wget -nv -O $HOME/bin/cbdinocluster https://github.com/couchbaselabs/cbdinocluster/releases/download/v0.0.41/cbdinocluster-linux-amd64
          chmod +x $HOME/bin/cbdinocluster
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Initialize cbdinocluster
        run: |
          cbdinocluster -v init --auto

      - name: Start couchbase cluster
        env:
          CLUSTERCONFIG: |
            nodes:
              - count: 3
                version: ${{ matrix.server }}
                services: [kv, n1ql, index, fts, cbas]
            docker:
              kv-memory: 2048
        run: |
          CBDC_ID=$(cbdinocluster -v alloc --def="${CLUSTERCONFIG}")
          cbdinocluster -v buckets add ${CBDC_ID} default --ram-quota-mb=100 --flush-enabled=true --num-replicas=2
          cbdinocluster -v collections add ${CBDC_ID} default _default test
          CBDC_CONNSTR=$(cbdinocluster -v connstr --tls $CBDC_ID)
          CBDC_IP=$(cbdinocluster -v ip $CBDC_ID)
          echo "CBDC_ID=$CBDC_ID" >> "$GITHUB_ENV"
          echo "CBDC_CONNSTR=$CBDC_CONNSTR" >> "$GITHUB_ENV"
          echo "CBDC_IP=$CBDC_IP" >> "$GITHUB_ENV"

      - name: Create fts index
        run: |
          curl -XPUT -H "Content-Type: application/json" -u Administrator:password http://${{ env.CBDC_IP }}:8094/api/index/basic_search_index -d '{"type": "fulltext-index","name": "basic_search_index","sourceType": "gocbcore","sourceName": "default","planParams": {"maxPartitionsPerPIndex": 1024,"indexPartitions": 1},"params": {"doc_config": {"docid_prefix_delim": "","docid_regexp": "","mode": "type_field","type_field": "type"},"mapping": {"analysis": {},"default_analyzer": "standard","default_datetime_parser": "dateTimeOptional","default_field": "_all","default_mapping": {"dynamic": true,"enabled": true},"default_type": "_default","docvalues_dynamic": true,"index_dynamic": true,"store_dynamic": true,"type_field": "_type"},"store": {"indexType": "scorch","segmentVersion": 15}},"sourceParams": {}}' 

      - uses: actions/checkout@v4

      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.4.3

      - name: Run tests
        timeout-minutes: 40
        env:
          CBDC_ID: # from above
          CBDC_CONNSTR: # from above
          RCBDINOID: ${{ env.CBDC_ID }}
          RCBCONNSTR: ${{ env.CBDC_CONNSTR }}
          RCBSERVER_VERSION: ${{ matrix.server }}
        run: |
          cargo test --color=always --no-fail-fast -- --nocapture

#      - name: Collect couchbase logs
#        timeout-minutes: 10
#        if: failure()
#        run: |
#          mkdir -p ./logs
#          cbdinocluster -v collect-logs $CBDC_ID ./logs
#
#      - name: Upload couchbase logs
#        if: failure()
#        uses: actions/upload-artifact@v3
#        with:
#          name: cbcollect-logs
#          path: ./logs/*
#          retention-days: 1
